apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-deployment
  name: hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-world-deployment
    spec:
      containers:
      - image: sanjeevbr38/testdemo:latest
        name: testdemo
        resources: {}
