apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    env: dev
    type: app
spec:
  containers:
  - image: sanjeevbr38/testdemo:latest
    name: hello-world-container
    ports:
    - containerPort: 8090
