name: Maven Build and SSH Deploy 

on:
  push:
    branches: [ "master" ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
  
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: nexus-snapshots
        server-username: NEXUS_USERNAME
        server-password: NEXUS_PASSWORD
        cache: maven
        
    - name: Publish to Nexus
      # Maven will now find the credentials in the generated settings.xml
      run: mvn deploy -DskipTests
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    - name: Build with Maven
      run: mvn clean package    

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
        name: build-artifact
        path: webapp/target
        
    - name: Change Ownership on Ansible Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.ANSIBLE_HOST }}
        username: ${{ secrets.ANSIBLE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Create the parent directory and fix ownership
          sudo mkdir -p /etc/ansible/opt/playbooks
          sudo chown -R ubuntu:ubuntu /etc/ansible
          
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

          # Clone if missing, otherwise Pull the latest
          if [ ! -d "/etc/ansible/opt/playbooks/.git" ]; then
            git clone git@github.com:brsanjeev88/hello-world-1.git /etc/ansible/opt/playbooks
          else
            cd /etc/ansible/opt/playbooks && git pull origin main
          fi
          
      
